[package]
# Semantic Versioning is used: https://semver.org/
version = "1.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["mike-wise"]

# The title and description fields are primarily for displaying extension info in UI
title = "SphereFlake Benchmark"
description="Spawn SphereFlakes in the scene using different techniques for benchmarking purposes"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Benchmark"

# Keywords for the extension
keywords = ["kit", "sphereflake", "benchmark"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import omni.example.spawn_prims".
[[python.module]]
# name = "omni.example.spawn_prims"
name = "omni.sphereflake"

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test" # UI testing extension
]

[python.pipapi]
requirements = ["nvidia-smi","nvidia-ml-py3"]
use_online_index = true
